logging:
   level:
      jdbc.sqlonly: DEBUG ## 이부분 추가.
      org.springframework: INFO
      org.springframework.web: DEBUG

spring:
   profiles:
      active: local
   mvc:
      view:
         prefix: /WEB-INF/views/ 
         suffix: .jsp
   datasource:
        url: jdbc:mysql://nkpl8b2jg68m87ht.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/yvkycdergykwvkp4?autoReconnect=true
        #url: jdbc:log4jdbc:mysql://nkpl8b2jg68m87ht.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/yvkycdergykwvkp4?autoReconnect=true
        username: g49ghwo2qt9ms0a0
        password: ts6plmm9bwlv7wmn
        driver-class-name: org.mariadb.jdbc.Driver
        #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        max-active: 1
        type: org.apache.tomcat.jdbc.pool.DataSource
        tomcat:
           max-active: 3
           initial-size: 1
           max-idle: 1
           min-idle: 1
   jpa:
      database: h2
      show-sql: true
      hibernate:
         ddl-auto: update
      properties:
         hibernate.format_sql: true
         hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
--- #local
spring:
   profiles: local

server:
   port: 8000
   ssl:
      key-store: keystore.p12
      key-store-password: wldrod2
      keyStoreType: PKCS12
      keyAlias: tomcat
   servlet: 
      jsp:
      init-parameters:
         development: truee
         
facebook:
  client:
    clientId: 783950902048254
    clientSecret: b7495564f3bc72b26990dabaf788e603
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/v3.0/me?fields=id, name, email, picture

google :
  client :
    clientId : 361321224931-7rnhths49neu5js8bjco1ng2asmm39tr.apps.googleusercontent.com
    clientSecret: XcOAZMx_ObyNvyIHA442mNxM
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo    
    
kakao:
  client:
    clientId: 8cccafaab6840d47fdbc6adc9868b451
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://kapi.kakao.com/v2/user/me
    
naver:
  client:
    clientId: Ae1kBIRbrivvB5hjA4_j
    clientSecret: z2NpthPjWF
    accessTokenUri: https://nid.naver.com/oauth2.0/token
    userAuthorizationUri: https://nid.naver.com/oauth2.0/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://openapi.naver.com/v1/nid/me

--- #dev
spring:
   profiles: dev

server:
   port: ${port:8000}
   
facebook:
  client:
    clientId: 805621019855659
    clientSecret: fdc6a7d7787f50c5a10029c2e0119003
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=id, name, email, picture

google :
  client :
    clientId : 361321224931-4uj2in7j3r4v7l6004864u3uv9moqg1h.apps.googleusercontent.com
    clientSecret: DbV3n3kwynhfm4XfTv9mCTyb
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo    
    
kakao:
  client:
    clientId: bfff8d6c1ad463c0c7f960cd6e3a25ef
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://kapi.kakao.com/v2/user/me
    
naver:
  client:
    clientId: Ae1kBIRbrivvB5hjA4_j
    clientSecret: z2NpthPjWF
    accessTokenUri: https://nid.naver.com/oauth2.0/token
    userAuthorizationUri: https://nid.naver.com/oauth2.0/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://openapi.naver.com/v1/nid/me

aws:
   access:
      key: ${AWS_ACCESS_KEY_ID}
   secret:
      key: ${AWS_SECRET_ACCESS_KEY}
   s3:
      bucket: aaa4285gradportfolio
   bucket:
      img:
         upload:
            path: aaa4285gradportfolio/board/
         file:
            path: s3.ap-northeast-2.amazonaws.com
      json:
         upload:
            path: aaa4285gradportfolio/json
         file:
            name: chart_data.json