spring:
   profiles:
      active: local
   mvc:
      view:
         prefix: /WEB-INF/views/ 
         suffix: .jsp
   
--- #local
spring:
   profiles: local

server:
   port: 8000
   ssl:
      key-store: keystore.p12
      key-store-password: wldrod2
      keyStoreType: PKCS12
      keyAlias: tomcat
   servlet: 
      jsp:
      init-parameters:
         development: truee
         
facebook:
  client:
    clientId: 783950902048254
    clientSecret: b7495564f3bc72b26990dabaf788e603
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

google :
  client :
    clientId : 361321224931-7rnhths49neu5js8bjco1ng2asmm39tr.apps.googleusercontent.com
    clientSecret: XcOAZMx_ObyNvyIHA442mNxM
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo    
    
kakao:
  client:
    clientId: 8cccafaab6840d47fdbc6adc9868b451
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://kapi.kakao.com/v2/user/me
    
naver:
  client:
    clientId: Ae1kBIRbrivvB5hjA4_j
    clientSecret: z2NpthPjWF
    accessTokenUri: https://nid.naver.com/oauth2.0/token
    userAuthorizationUri: https://nid.naver.com/oauth2.0/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://openapi.naver.com/v1/nid/me

--- #dev
spring:
   server:
   port: ${port:8000}
   profiles: dev
   
facebook:
  client:
    clientId: 805621019855659
    clientSecret: fdc6a7d7787f50c5a10029c2e0119003
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

google :
  client :
    clientId : 361321224931-4uj2in7j3r4v7l6004864u3uv9moqg1h.apps.googleusercontent.com
    clientSecret: DbV3n3kwynhfm4XfTv9mCTyb
    accessTokenUri: https://www.googleapis.com/oauth2/v4/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
    clientAuthenticationScheme: form
    scope:
    - email
    - profile
  resource:
    userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo    
    
kakao:
  client:
    clientId: bfff8d6c1ad463c0c7f960cd6e3a25ef
    accessTokenUri: https://kauth.kakao.com/oauth/token
    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://kapi.kakao.com/v2/user/me
    
naver:
  client:
    clientId: Ae1kBIRbrivvB5hjA4_j
    clientSecret: z2NpthPjWF
    accessTokenUri: https://nid.naver.com/oauth2.0/token
    userAuthorizationUri: https://nid.naver.com/oauth2.0/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://openapi.naver.com/v1/nid/me

